//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_M_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int Bill_ID { get; set; }
        public Nullable<int> C_ID { get; set; }
        public Nullable<int> Event_ID { get; set; }
        public Nullable<int> Ticket_ID { get; set; }
        public Nullable<int> Transport { get; set; }
        public Nullable<int> Food { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Event Event { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
