//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_M_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Billings = new HashSet<Billing>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int Event_ID { get; set; }
        public string Event_Name { get; set; }
        public Nullable<int> Venue_ID { get; set; }
        public Nullable<int> Cattering_ID { get; set; }
        public Nullable<int> Transport_ID { get; set; }
        public Nullable<int> Music_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billing> Billings { get; set; }
        public virtual Cattering Cattering { get; set; }
        public virtual Music Music { get; set; }
        public virtual Transport Transport { get; set; }
        public virtual Venue Venue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
